apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: surya
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.26.1
          ports:
            - containerPort: 80
